import { useEffect, useState } from 'react'
import { BarChart3, Download, LoaderCircle, RefreshCw } from 'lucide-react'
import Header from '../components/admin/Header'
import Sidebar from '../components/admin/Sidebar'
import { getReportSummary } from '../services/reportApi'
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`
function ReportsPage(){const [open,setOpen]=useState(false),[data,setData]=useState(null),[error,setError]=useState(''); async function load(){try{setData(await getReportSummary())}catch(e){setError(e.response?.data?.message||'Unable to load reports')}} useEffect(()=>{load()},[]); function download(){if(!data)return;const s=data.summary;const rows=[['Metric','Value'],['Students',s.students],['Rooms',s.rooms],['Beds',s.beds],['Fees billed',s.fees.billed],['Fees paid',s.fees.paid],['Fees balance',s.fees.balance],['Payments total',s.payments.total],['Payment count',s.payments.count],...s.complaints.map(x=>[`Complaints - ${x._id}`,x.count])];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='jds-hostel-report.csv';a.click();URL.revokeObjectURL(a.href)}return <div className="admin-app"><Sidebar isOpen={open} onClose={()=>setOpen(false)}/>{open&&<button className="sidebar-overlay" onClick={()=>setOpen(false)}/>}<div className="admin-content"><Header onMenuClick={()=>setOpen(true)}/><main className="student-main"><div className="student-page-intro"><div><p className="eyebrow">Management</p><h1>Reports</h1><p>Live totals from the hostel database. Export anytime.</p></div><div className="row-actions"><button className="secondary-button" onClick={load}><RefreshCw size={15}/> Refresh</button><button className="primary-button" onClick={download} disabled={!data}><Download size={15}/> Export CSV</button></div></div>{error&&<div className="error-banner">{error}</div>}{!data?<div className="student-loading"><LoaderCircle className="spin" size={26}/> Loading report...</div>:<div className="stats-grid"><Card label="Students" value={data.summary.students}/><Card label="Rooms" value={data.summary.rooms}/><Card label="Beds" value={data.summary.beds}/><Card label="Fees billed" value={money(data.summary.fees.billed)}/><Card label="Fees paid" value={money(data.summary.fees.paid)}/><Card label="Outstanding" value={money(data.summary.fees.balance)}/><Card label="Payments" value={data.summary.payments.count}/><Card label="Payment value" value={money(data.summary.payments.total)}/></div>}<section className="panel student-table-panel"><div className="table-panel-heading"><div><h2>Complaint breakdown</h2></div></div>{data?.summary.complaints?.length?<div className="student-table-scroll"><table className="student-table"><thead><tr><th>Status</th><th>Count</th></tr></thead><tbody>{data.summary.complaints.map(x=><tr key={x._id}><td>{x._id}</td><td>{x.count}</td></tr>)}</tbody></table></div>:<div className="student-empty"><BarChart3 size={28}/><h3>No complaint data</h3></div>}</section></main></div></div>}
function Card({label,value}){return <article className="stat-card"><span className="stat-card__label">{label}</span><strong className="stat-card__value">{value}</strong><span className="stat-card__detail">Live database value</span></article>}
export default ReportsPage
